#!/bin/bash

set -e

wget -q https://dl.influxdata.com/telegraf/releases/telegraf-${telegraf_version}_linux_${telegraf_arch}.tar.gz -O /tmp/telegraf-${telegraf_version}_linux_${telegraf_arch}.tar.gz
tar xf /tmp/telegraf-${telegraf_version}_linux_${telegraf_arch}.tar.gz -C /tmp/
rsync -r /tmp/telegraf/* /
